### ISSUE TITLE
Cannot use this repo as a GitHub repo template

### ISSUE THREAD

**Issue by tnir** [johanbrandhorst/grpc-gateway-boilerplate#19]
We cannot use this repo as a template as [statik/statik.go](https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/76a1d746cc6a4959b3331d5886f786b54294fe31/statik/statik.go) has 13.7MB in this repo as of 2020-11-04, which was recently introduced in #17.

| File size | before #17 (= after #14) | after #17 |
|-|-|-|
| `statik/statik.go` | 6.8MB | 13.7MB |

Anyone can reproduce this by starting with `Use this template` button to see the following error:

> We're sorry, something went wrong.
> We were unable to clone johanbrandhorst/grpc-gateway-boilerplate's contents into `{username,orgname}/{reponame}`. The template you used includes files that are larger than 10 megabytes. Please ask johanbrandhorst to remove those files from the template and try again.

cf. `https://github.com/education/classroom/issues/2521`

**Comment by tnir** [comment]
@johanbrandhorst @dmitris Do you have any thoughts on it?

**Comment by johanbrandhorst** [comment]
Thanks for raising this issue, I wasn't aware it was a problem :smile:. I've opened #20 which shrinks `statik.go` to 2.9MB in my testing by removing the `*.map` files in the OpenAPI UI distribution.

**Comment by tnir** [comment]
Thanks for a quick hack!! 😃
