### ISSUE TITLE
Cannot find module for path embed

### ISSUE THREAD

**Issue by p7ac** [johanbrandhorst/grpc-gateway-boilerplate#34]
Hi there, thanks for providing this boilerplate repo.

I've checked this repo out and followed the instructions, running `make install` then `make generate`.

When running `go main.go run` the command errors out with this message:

`build github.com/johanbrandhorst/grpc-gateway-boilerplate: cannot find module for path embed`

Do you have any idea what could be happening here?

**Comment by marcosnils** [comment]
You need to use go1.16+ to build this project. The `embed` directive was added starting that release.

Cheers!

**Comment by johanbrandhorst** [comment]
Thanks for your interest in the project! Marcos is right, you'll need at least Go 1.16 to build the project. I have updated the README to make that clear.

**Comment by p7ac** [comment]
Thanks so much - I’ll update and give that a try.

Alasdair Campbell
/PURPLE SEVEN/

T: +44 (0)7952 286 005
E: ***@***.***
W: www.purpleseven.com

IC2.4, The TechnoCentre
Coventry University Technology Park
Puma Way
Coventry, CV1 2TT
________________________________
