### ISSUE TITLE
Handling streaming responses in swagger web page

### ISSUE THREAD

**Issue by Closius** [johanbrandhorst/grpc-gateway-boilerplate#37]
Hi, thank you for the project!

Is there a simplest way to handle streaming responses in Swagger web page (which is based on auto gen swagger .json)?

**Comment by johanbrandhorst** [comment]
The default swagger UI unfortunately does not support streaming responses, but you can implement a client yourself that can use server side streaming by parsing the specified structure in the swagger file as the object in newline delimited JSON responses.
