### ISSUE TITLE
updating to new buf manifest/config versions

### ISSUE THREAD

**Issue by insanitywholesale** [johanbrandhorst/grpc-gateway-boilerplate#39]
First off I'd like to thank you for your awesome work, this repository has been an incredibly valuable source for learning how to structure a gRPC project in Go that uses gRPC-gateway.

I started writing my own template last year to add a few more things that I wanted to be figured out when I want to write a new service and it can be found [in this repository on gitlab](https://gitlab.com/insanitywholesale/go-grpc-microservice-template/) (it's also mirrored [here on github](https://github.com/insanitywholesale/go-grpc-microservice-template)).

Currently, my `buf.yaml` and `buf.gen.yaml` look a lot like yours and there is also `wouldbe-buf.work.yaml` because it currently doesn't work if you try to upgrade or if  you just follow the steps in the [official tour](https://docs.buf.build/tour/configure-and-build).

This led me to spend many evenings trying to troubleshoot it until I read a blog post that provided just enough details to figure out the issue.
In [this commit on a feature branch](https://gitlab.com/insanitywholesale/go-grpc-microservice-template/-/commit/1b590ad48ce51fc14db330d443a2b6aa71e7d191) I discovered that there is indeed a way to upgrade to it although it's less than ideal.

In rough order:
- In each directory holding `.proto` files, put a simple `buf.yaml` with the `deps` key and then run `buf mod update` to create the lock file
- If you're using `v1`, `v2` and so on for different versions of the API, you need to do the above step seemingly for all directories until the repo root but I haven't done extensive testing. I had to do it in my `protos/` directory that has two subdirectories/packages called `v1` and `v2`
- At the root of the project, `buf.work.yaml` can be just
```
version: v1
directories:
  - proto
```
- Again at the root of the project, `buf.yaml` doesn't need the `build` key so it can just have the necessary `name`, `version` and `deps`, of course with `version` going from `v1beta1` to `v1` (v1 is where `build` and consequently `build.root` was removed)
- Finally, run `buf mod update` at the root and then `buf generate` which shouldn't result in any issues

That's what worked for me, I hope this helps somewhat in case you were holding back from upgrading due to the inability for buf to pull in `.proto` dependencies or generate files properly.
Let me know if there is any additional information I can provide in case you wish to update the way `buf` stuff is handled, otherwise feel free to close the issue, I just wanted to share my experience dealing with this problem and what I did to fix it.

**Comment by johanbrandhorst** [comment]
Hi, thanks for the kind words! I think we should be able to use `buf beta migrate-v1beta1` to do most of the work for us. I'd forgotten I hadn't updated this repo yet, I should get to it :).

**Comment by insanitywholesale** [comment]
I didn't even know such a command existed! Great to know it can be done more easily than what I previously thought
